Add lang util tests
Diffblue-benchmarks/Ffay-lanproxy pull request #1
Opened 2019-07-05 14:04 UTC by ThomasPerkins1123

2019-07-09 10:34 UTC, paulkennethkent approved these changes

2019-07-09 10:35 UTC, paulkennethkent requested changes
Use the new setting to generate these tests? They should be better

2019-07-10 10:55 UTC, paulkennethkent commented on proxy-common/src/test/java/org/fengfei/lanproxy/common/LangUtilTest.java
> +}
New line needed.

2019-07-11 09:00 UTC, paulkennethkent requested changes

2019-07-11 09:00 UTC, paulkennethkent commented on pom.xml
> +            <groupId>org.powermock</groupId>
I don't think you need powermock

2019-07-11 09:00 UTC, paulkennethkent commented on pom.xml
> +            <artifactId>deeptestutils</artifactId>
I would also get rid of this and the `staticInitOutputVoid` test. Let's assume in this PR that we are using test-ranker and no-trivial test option which will remove that test.

2019-07-11 09:01 UTC, paulkennethkent commented on proxy-common/src/test/java/org/fengfei/lanproxy/common/LangUtilTest.java
> +  public void staticInitOutputVoid() throws InvocationTargetException {
Remove this test

2019-07-16 12:52 UTC, paulkennethkent approved these changes

2019-07-16 14:31 UTC, petersear approved these changes

2019-09-04 08:50 UTC, closed without merging